server:
  port: 8885
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ProductManager-Service?createDatabaseIfNotExist=true
    username: root
    password: S0meth!ng976431
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: ProductManager
  cloud:
    config:
      enabled: true
      uri: http://localhost:8880/
      name: product-manager
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/