server:
  port: 8886
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${productDbHost:localhost}:${productDbPort:3306}/${productDbName:product-db}?createDatabaseIfNotExist=true
    username: ${productDbUsername:root}
    password: ${productDbPassword:S0meth!ng976431}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: product-service
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServerUrl:localhost}:${eurekaServerPort:7881}/eureka/