spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
  flyway:
    connect-retries: -1
server:
  port: 9990