version: '3'
services:
  spring-cloud-config:
    container_name: spring-cloud-config
    network_mode: host
    build:
      context: ./SpringCloudConfig
    ports:
      - "8880:8880"
  eureka-server:
    container_name: eureka-server
    network_mode: host
    build:
      context: ./EurekaServer
    ports:
      - "8881:8881"
    depends_on:
      - spring-cloud-config
