server:
  port: 9991
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: maiyonaisu1102@gmail.com
    password: xvsj baoi fgze ymib
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
        starttls:
          enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer