version: '3'
name: spring-microservices
services:
  spring-cloud:
    container_name: spring-cloud
    restart: always
    networks:
      - maiyon-network
    build:
      context: ./SpringCloud
    ports:
      - "8880:8880"
    expose:
      - 8880
    healthcheck:
      test: [ "CMD-SHELL", "netstat -an | grep -q 8880" ]
  eureka-server:
    container_name: eureka-server
    restart: always
    networks:
      - maiyon-network
    environment:
      - springCloudUrl=spring-cloud
      - springCloudPort=8880
    build:
      context: ./EurekaServer
    ports:
      - "8881:8881"
    expose:
      - 8881
    depends_on:
      spring-cloud:
        condition: service_healthy
networks:
  maiyon-network:
    driver: bridge
