spring:
  application:
    name: auth-service
  cloud:
    config:
      discovery:
        enabled: true
      uri: http://localhost:8880/
      name: auth-service
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/
expired: 3153600000
secret_key: Maiyonaisu1102@gmail.com